# Site settings
title: Esporo
tagline: A comunidade brasileira de Spore
description: >-
  Comunidade para jogadores de Spore, com conteúdos personalizados para download; tutoriais; fóruns de discussão e suporte; e as últimas notícias sobre o jogo.
logo: "/assets/images/logo.png"

lang: pt-BR
timezone: "America/Sao_Paulo"

email: contato@esporo.net
url: "https://esporo.net"
baseurl: ""

# Build settings
permalink: "/:year/:month/:title/"

plugins:
  - jekyll-feed
  - jekyll-json-feed
  - jekyll-seo-tag
  - jekyll-sitemap
